import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Filter from "./components/filter/Filter";

const popins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={popins.className}>
        <main>
          <div className="container">
            <div className="wrapper">
              <Navbar />
              <Filter />
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
